; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:lilygo-t-display-S3-touch]
board = esp32s3
board_build.partitions = support_files/custom_16Mb.csv
board_upload.speed = 921600
build_src_filter =${env.build_src_filter} +<../boards/lilygo-t-display-s3-touch>
build_flags =
	${env.build_flags}
	-DARDUINO_USB_MODE=1

	-DDEVICE_NAME='"Lilygo T-Display S3"'
	-DDISABLE_OTA

	-DBOARD_HAS_PSRAM=1
	-DARDUINO_USB_CDC_ON_BOOT=1

	-DLAUNCHER_GPIO_KEYS='{{"Right", 14}}' # Choose among available GPIO to start Launcher when booting

	-DHAS_2_BUTTONS=1
	-DBUTTONS_IDF_COMPONENT=1 # hal_buttons_init_2/hal_buttons_poll_2 (src/hal/inputs/buttons.cpp)
	-DHAS_TOUCH=1
	-DTOUCH_CTRL_CST8XX=1 # hal_touch_init/hal_touch_read (src/hal/inputs/touch.cpp)

    -DROTATION=3
	-DANALOG_BAT_PIN=4

	-D TFT_DATABUS_N=2        # Arduino_ESP32PAR8Q
	-D TFT_DISPLAY_DRIVER_N=1  # Arduino_ST7789
	-D TFT_WIDTH=170
	-D TFT_HEIGHT=320
	-D TFT_CS=6
	-D TFT_DC=7
	-D TFT_RST=5
	-D TFT_WR=8
	-D TFT_RD=9
	-D TFT_D0=39
	-D TFT_D1=40
	-D TFT_D2=41
	-D TFT_D3=42
	-D TFT_D4=45
	-D TFT_D5=46
	-D TFT_D6=47
	-D TFT_D7=48
	-D TFT_BL=38

	-D TFT_IPS=1
	-D TFT_COL_OFS1=35
	-D TFT_ROW_OFS1=0
	-D TFT_COL_OFS2=35
	-D TFT_ROW_OFS2=0

	-DUSE_SD_MMC=1
	-DSDM=SD_MMC
	-DPIN_SD_CMD=13
	-DPIN_SD_CLK=11
	-DPIN_SD_D0=12

lib_deps =
	${env.lib_deps}
	https://github.com/bmorcelli/ESP32_Button

lib_ignore =
	XPowersLib
