[env:waveshare-esp32-s3-touch-amoled-206]
board = esp32s3
board_build.partitions = support_files/custom_32Mb.csv

board_build.arduino.memory_type = qio_qspi
board_upload.flash_size = 32MB
board_upload.maximum_size = 33554432

build_src_filter =${env.build_src_filter} +<../boards/waveshare-esp32-s3-touch-amoled-206>
build_flags =
	${env.build_flags}
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1

	-D DEVICE_NAME='"Waveshare ESP32-S3 Touch AMOLED 2.06"'
	-D OTA_TAG='"waveshare_amoled_206"'
	-D OTA_EXTRA='"esp=S3"'
	-D LAUNCHER_DEFAULT_SPIFFS_THRESHOLD=0x500000

	-D ROTATION=0
	-D DIMMER_SETUP=20
	-D HAS_2_BUTTONS=1
	-D BUTTONS_IDF_COMPONENT=1
	-D HAS_TOUCH=1
	-D TOUCH_CTRL_FT6X36=1

	-D ROUND_EDGE_SIZE=57 # to use when the rounded edges hide text or icons on screen
	-D TFT_DATABUS_N=1			# Arduino_ESP32QSPI
	-D TFT_DISPLAY_DRIVER_N=41	# CO5300
	-D TFT_WIDTH=502
	-D TFT_HEIGHT=410
	-D TFT_CS=12
	-D TFT_RST=8
	-D TFT_SCLK=11
	-D TFT_D0=4
	-D TFT_D1=5
	-D TFT_D2=6
	-D TFT_D3=7
	-D TFT_IPS=0
	-D TFT_COL_OFS1=0
	-D TFT_ROW_OFS1=22
	-D TFT_COL_OFS2=0
	-D TFT_ROW_OFS2=22

	-D SDCARD_CS=17
	-D SDCARD_SCK=2
	-D SDCARD_MISO=3
	-D SDCARD_MOSI=1


lib_deps =
	${env.lib_deps}
	https://github.com/bmorcelli/ESP32_Button
