[env:waveshare-esp32-s3-lcd-147]
board = esp32s3
board_build.partitions = support_files/custom_16Mb.csv
board_upload.speed = 921600
build_src_filter = ${env.build_src_filter} +<../boards/waveshare-esp32-s3-lcd-147>
build_flags =
	${env.build_flags}
	-DBOARD_HAS_PSRAM=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1

	-DDEVICE_NAME='"Waveshare ESP32-S3 LCD 1.47"'
	-DDISABLE_OTA
	-DHAS_1_BUTTON=1
	-DROTATION=1

	-D TFT_DATABUS_N=0        # Arduino_HWSPI
	-D TFT_DISPLAY_DRIVER_N=1  # Arduino_ST7789
	-DUSER_SETUP_LOADED
	-DTFT_RGB_ORDER=TFT_BGR
	-DINIT_SEQUENCE_3
	-DCGRAM_OFFSET
	-DTFT_WIDTH=172
	-DTFT_HEIGHT=320
	-DTFT_MISO=-1
	-DTFT_MOSI=45
	-DTFT_SCLK=40
	-DTFT_CS=42
	-DTFT_DC=41
	-DTFT_RST=39
	-DTFT_BL=48
	-DTFT_IPS=1
	-DTFT_COL_OFS1=34
	-DTFT_ROW_OFS1=0
	-DTFT_COL_OFS2=34
	-DTFT_ROW_OFS2=0
	-DSPI_FREQUENCY=40000000
	-DSPI_READ_FREQUENCY=20000000
	-DUSE_HSPI_PORT=1

	-DUSE_SD_MMC=1
	-D SDM=SD_MMC

	-DPIN_SD_CLK=14
	-DPIN_SD_CMD=15
	-DPIN_SD_D0=16
	-D SDCARD_CS=-1
	-D SDCARD_SCK=PIN_SD_CLK
	-D SDCARD_MISO=PIN_SD_D0
	-D SDCARD_MOSI=PIN_SD_CMD

[env:waveshare-esp32-c5-lcd-147]
board = esp32c5
board_build.partitions = support_files/custom_4Mb.csv
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
board_upload.speed = 921600
build_src_filter =${env.build_src_filter} +<../boards/waveshare-esp32-s3-lcd-147>
build_flags =
	${env.build_flags}
	-DDEVICE_NAME='"Waveshare ESP32-C5 LCD 1.47"'
	-DDISABLE_OTA
	-DHAS_1_BUTTON=1
	-DROTATION=1

	-D TFT_DATABUS_N=0
	-D TFT_DISPLAY_DRIVER_N=1
	-DST7789_DRIVER=1
	-DTFT_WIDTH=172
	-DTFT_HEIGHT=320
	-DTFT_BL=10
	-DTFT_MISO=5
	-DTFT_MOSI=6
	-DTFT_SCLK=7
	-DTFT_CS=23
	-DTFT_DC=24
	-DTFT_RST=26

	-DTFT_IPS=1
	-DTFT_COL_OFS1=34
	-DTFT_ROW_OFS1=0
	-DTFT_COL_OFS2=34
	-DTFT_ROW_OFS2=0

	;SD Card Setup pins
	-DSDCARD_CS=4
	-DSDCARD_SCK=7
	-DSDCARD_MISO=5
	-DSDCARD_MOSI=6

[env:waveshare-esp32-c6-lcd-147]
board = esp32c6
board_build.partitions = support_files/custom_8Mb.csv
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
board_upload.speed = 921600
build_src_filter =${env.build_src_filter} +<../boards/waveshare-esp32-s3-lcd-147>
build_flags =
	${env.build_flags}
	-DDEVICE_NAME='"Waveshare ESP32-C6 LCD 1.47"'
	-DDISABLE_OTA
	-DHAS_1_BUTTON=1
	-DROTATION=1

	-D TFT_DATABUS_N=0
	-D TFT_DISPLAY_DRIVER_N=1
	-DST7789_DRIVER=1
	-DTFT_WIDTH=172
	-DTFT_HEIGHT=320
	-DTFT_BL=22
	-DTFT_MISO=5
	-DTFT_MOSI=6
	-DTFT_SCLK=7
	-DTFT_CS=14
	-DTFT_DC=15
	-DTFT_RST=21

	-DTFT_IPS=1
	-DTFT_COL_OFS1=34
	-DTFT_ROW_OFS1=0
	-DTFT_COL_OFS2=34
	-DTFT_ROW_OFS2=0

	;SD Card Setup pins
	-DSDCARD_CS=4
	-DSDCARD_SCK=7
	-DSDCARD_MISO=5
	-DSDCARD_MOSI=6


[env:waveshare-esp32-c6-lcd-130]
board = esp32c6
board_build.partitions = support_files/custom_4Mb.csv
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
board_upload.speed = 921600
build_src_filter =${env.build_src_filter} +<../boards/waveshare-esp32-s3-lcd-147>
build_flags =
	${env.build_flags}
	-DDEVICE_NAME='"Waveshare ESP32-C6 LCD 1.3"'
	-DDISABLE_OTA
	-DHAS_1_BUTTON=1
	-DROTATION=1

	-D TFT_DATABUS_N=0
	-D TFT_DISPLAY_DRIVER_N=1
	-DST7789_DRIVER=1
	-DTFT_WIDTH=240
	-DTFT_HEIGHT=240
	-DTFT_BL=22
	-DTFT_MISO=5
	-DTFT_MOSI=6
	-DTFT_SCLK=7
	-DTFT_CS=14
	-DTFT_DC=15
	-DTFT_RST=21

	-DTFT_IPS=1
	-DTFT_COL_OFS1=0
	-DTFT_ROW_OFS1=80
	-DTFT_COL_OFS2=0
	-DTFT_ROW_OFS2=80

	;SD Card Setup pins
	-DSDCARD_CS=4
	-DSDCARD_SCK=7
	-DSDCARD_MISO=5
	-DSDCARD_MOSI=6

