; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-paper-color]
board = esp32s3
board_build.partitions = support_files/custom_16Mb.csv
board_build.arduino.memory_type = qio_opi
board_upload.speed = 921600
build_src_filter =${env.build_src_filter} +<../boards/m5stack-paper-color>
build_flags =
	${env.build_flags}
	-DM5STACK
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1

	-DDEVICE_NAME='"M5Stack Paper Color"'
	-DOTA_TAG='"paper"'
	-DOTA_EXTRA='"esp=S3"'

	-DUSE_M5GFX=1
	-DUSE_CANVAS=1
	-DE_PAPER_DISPLAY=1

	-DLAUNCHER_GPIO_KEYS='{{"Top",1}, {"Up", 9}, {"Down", 10}}' # Choose among available GPIO to start Launcher when booting

	-DROTATION=0
	-DDIMMER_SETUP=0

	-DHEADLESS=1
	-DHEADLESS_WITH_TFT=1

	-DFP=1
	-DFM=3
	-DFG=5

	-DTFT_WIDTH=400
	-DTFT_HEIGHT=600

	-DSDCARD_CS=47
	-DSDCARD_SCK=15
	-DSDCARD_MISO=14
	-DSDCARD_MOSI=13


lib_deps =
	${env.lib_deps}
	m5stack/M5Unified @ ^0.2.17
	m5stack/M5GFX @ ^0.2.21

lib_ignore =
	SensorLib
	XPowersLib
	GFX Library for Arduino
