; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

##################################### NM-CYD-C5 (ESP32-C5) ####################################################
[env:NM-CYD-C5]
board = esp32c5
board_build.partitions = support_files/custom_16Mb.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
build_src_filter = ${env.build_src_filter} +<../boards/NM-CYD-C5>
build_flags =
	${env.build_flags}
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1


	-DDEVICE_NAME='"NM-CYD-C5"'
	-DOTA_TAG='"NM-CYD-C5"'
	-DHAS_TOUCH=1

	-DDIMMER_SETUP=60

	-DROTATION=3

	-D TFT_DATABUS_N=0        # Arduino_HWSPI
	-D TFT_DISPLAY_DRIVER_N=1  # Arduino_ST7789
	-DTFT_WIDTH=240
	-DTFT_HEIGHT=320
	-DTFT_BL=25
	-DTFT_RST=-1
	-DTFT_DC=24
	-DTFT_MISO=2
	-DTFT_MOSI=7
	-DTFT_SCLK=6
	-DTFT_CS=23
	-DTOUCH_CS=1

	-DTFT_IPS=0
	-DTFT_COL_OFS1=0
	-DTFT_ROW_OFS1=0
	-DTFT_COL_OFS2=0
	-DTFT_ROW_OFS2=0

	-D HAS_RESISTIVE_TOUCH=1
	-D TOUCH_CTRL_XPT2046=1 # hal_touch_init/hal_touch_read (src/hal/inputs/touch.cpp)
	-DCYD28_TouchR_CAL_XMIN=185
	-DCYD28_TouchR_CAL_XMAX=3700
	-DCYD28_TouchR_CAL_YMIN=250
	-DCYD28_TouchR_CAL_YMAX=3800
	-DCYD28_DISPLAY_HOR_RES_MAX=320
	-DCYD28_DISPLAY_VER_RES_MAX=240

	-DTOUCH_XPT2046_SPI=1
	-DCYD28_TouchR_IRQ=-1
	-DCYD28_TouchR_MISO=TFT_MISO
	-DCYD28_TouchR_MOSI=TFT_MOSI
	-DCYD28_TouchR_CLK=TFT_SCLK
	-DCYD28_TouchR_CS=1

	-DSDCARD_CS=10
	-DSDCARD_SCK=TFT_SCLK
	-DSDCARD_MISO=TFT_MISO
	-DSDCARD_MOSI=TFT_MOSI

lib_ignore =
	SensorLib
	XPowersLib
