; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:lilygo-t-display-c5]
board = esp32c5
board_build.partitions = support_files/custom_16Mb.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
build_src_filter =${env.build_src_filter} +<../boards/lilygo-t-display-c5>
build_flags =
	${env.build_flags}
	-DBOARD_HAS_PSRAM=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1

	-DDEVICE_NAME='"Lilygo T-Display C5"'
	-DOTA_TAG='"t-display-c5"'

	-D HAS_2_BUTTONS=1
	-D BUTTONS_IDF_COMPONENT=1 # hal_buttons_poll_2 (src/hal/inputs/buttons.cpp) via ESP32_Button

	-D LAUNCHER_GPIO_KEYS='{{"Gpio 0", 0}}' # Choose among available GPIO to start Launcher when booting

    -DROTATION=3

	-D TFT_DATABUS_N=0        # Arduino_HWSPI
	-D TFT_DISPLAY_DRIVER_N=1  # Arduino_ST7789
	-D TFT_WIDTH=170
	-D TFT_HEIGHT=320
	-D TFT_BL=25
	-D TFT_MISO=6
	-D TFT_MOSI=9
	-D TFT_SCLK=7
	-D TFT_CS=26
	-D TFT_DC=8
	-D TFT_RST=23
	-D TOUCH_CS=-1

	-D TFT_IPS=1
	-D TFT_COL_OFS1=35
	-D TFT_ROW_OFS1=0
	-D TFT_COL_OFS2=35
	-D TFT_ROW_OFS2=0

	-D SDCARD_CS=27
	-D SDCARD_SCK=TFT_SCLK
	-D SDCARD_MISO=TFT_MISO
	-D SDCARD_MOSI=TFT_MOSI

lib_deps =
	${env.lib_deps}
	https://github.com/bmorcelli/ESP32_Button

