; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:lilygo-t-deck-pro]
board = esp32s3
board_build.partitions = support_files/custom_16Mb.csv
board_upload.speed = 921600
build_src_filter =${env.build_src_filter} +<../boards/lilygo-t-deck-pro>
build_flags =
	${env.build_flags}
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1

	-DDEVICE_NAME='"Lilygo T-Deck Pro"'
	-DOTA_TAG='"t-deck-pro"'
	-DE_PAPER_DISPLAY=1

	-DRESERVED_NAV_KEYS='"wasd"' # Up/Down/Prev/Next — see interface.cpp InputHandler
    -DROTATION=0 # 0,2 Portrait, 1,3 to landscape
	-DDIMMER_SETUP=0

	-DHAS_TOUCH=1
	-DTOUCH_CTRL_CST8XX=1 # hal_touch_init/hal_touch_read (src/hal/inputs/touch.cpp)
	-DHAS_KEYBOARD=1

	-DPMIC_BQ25896=1
	-DGAUGE_BQ27220=1

	-D USE_GXEPD2=1
	-DGXEPD2_PANEL=GxEPD2_310_GDEQ031T10
	-DGXEPD2_FULL_REFRESH_INTERVAL=0 ; Disable full refresh interval
	-DTFT_CS=34
	-DTFT_DC=35
	-DTFT_RST=-1
	-DTFT_BUSY=37
	-DTFT_SCLK=36
	-DTFT_MOSI=33
	-DTFT_MISO=47
	-DTFT_WIDTH=240
	-DTFT_HEIGHT=320

	-DSDCARD_CS=48
	-DSDCARD_SCK=36
	-DSDCARD_MOSI=33
	-DSDCARD_MISO=47

lib_deps =
	${env.lib_deps}
	zinggjm/GxEPD2 @ ^1.6.4
	adafruit/Adafruit TCA8418 @ ^1.0.2

lib_ignore =
	GFX Library for Arduino
