; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:Marauder-v8]
board = esp32c5
board_build.partitions = support_files/custom_8Mb2.csv
build_src_filter =${env.build_src_filter} +<../boards/marauder-v8>
build_flags =
	${env.build_flags}
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1

	-DDEVICE_NAME='"Marauder v8"'
	-DOTA_TAG='"marauder-v8"'

    -DROTATION=0

	-DHAS_TOUCH=1
	-D TFT_DATABUS_N=0        # Arduino_HWSPI
	-D TFT_DISPLAY_DRIVER_N=4  # Arduino_ILI9341
	-DTFT_MISO=2
	-DTFT_MOSI=7
	-DTFT_SCLK=6
	-DTFT_CS=23
	-DTFT_DC=24
	-DTFT_RST=-1
	-DTFT_BL=8
	-DTOUCH_CS=3

	-D TFT_IPS=0
	-D TFT_WIDTH=240
	-D TFT_HEIGHT=320
	-D TFT_COL_OFS1=0
	-D TFT_ROW_OFS1=0
	-D TFT_COL_OFS2=0
	-D TFT_ROW_OFS2=0

	-DSDCARD_CS=10
	-DSDCARD_SCK=TFT_SCLK
	-DSDCARD_MISO=TFT_MISO
	-DSDCARD_MOSI=TFT_MOSI

	-D HAS_RESISTIVE_TOUCH=1
	-D TOUCH_CTRL_XPT2046=1 # hal_touch_init/hal_touch_read (src/hal/inputs/touch.cpp)
	-D CYD28_TouchR_IRQ=-1
	-D CYD28_TouchR_MISO=TFT_MISO
	-D CYD28_TouchR_MOSI=TFT_MOSI
	-D CYD28_TouchR_CLK=TFT_SCLK
	-D CYD28_TouchR_CS=3
	-D SPI_TOUCH_FREQUENCY=2500000


lib_ignore =
	SensorLib
	XPowersLib
