; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:Marauder-Mini]
board = esp32
board_build.f_flash = 80000000L
board_build.partitions = support_files/custom_4Mb.csv
build_src_filter =${env.build_src_filter} +<../boards/marauder-mini>
build_flags =
	${env.build_flags}
	-DDEVICE_NAME='"Marauder Mini"'
	-DOTA_TAG='"marauder-mini"'

	-DROTATION=0
	-D HAS_5_BUTTONS=1
	-DLAUNCHER_GPIO_KEYS='{{"Sel", 34}, {"Up", 36}, {"Down", 35}, {"Left", 13}, {"Right", 39}}' # Choose among available GPIO to start Launcher when booting

	-DFP=1
	-DFM=1
	-DFG=2

	-D TFT_DATABUS_N=0        # Arduino_HWSPI
	-D TFT_DISPLAY_DRIVER_N=0  # Arduino_ST7735
	-DTFT_WIDTH=128
	-DTFT_HEIGHT=128
	-DTFT_MISO=19
	-DTFT_MOSI=23
	-DTFT_SCLK=18
	-DTFT_BL=32
	-DTFT_CS=17
	-DTFT_DC=16
	-DTFT_RST=5

	# // 1.5" GREENTAB C 128x128
	-D TFT_IPS=0
	-D TFT_COL_OFS1=2
	-D TFT_ROW_OFS1=3
	-D TFT_COL_OFS2=0
	-D TFT_ROW_OFS2=0

	-DSDCARD_CS=4
	-DSDCARD_SCK=18
	-DSDCARD_MISO=19
	-DSDCARD_MOSI=23

lib_ignore =
	SensorLib
	XPowersLib

[env:Marauder-v7]
board = esp32
board_build.f_flash = 80000000L
board_build.partitions = support_files/custom_4Mb.csv
build_src_filter =${env.build_src_filter} +<../boards/marauder-mini>
build_flags =
	${env.build_flags}
	-DDEVICE_NAME='"Marauder V7"'
	-DOTA_TAG='"marauder-v7"'
	-D HAS_5_BUTTONS=1

	-DROTATION=0

	-D TFT_DATABUS_N=0        # Arduino_HWSPI
	-D TFT_DISPLAY_DRIVER_N=4  # Arduino_ILI9341
	-DTFT_WIDTH=240
	-DTFT_HEIGHT=320
	-DTFT_MISO=19
	-DTFT_MOSI=23
	-DTFT_SCLK=18
	-DTFT_CS=17
	-DTFT_DC=26
	-DTFT_RST=-1
	-DTFT_BL=32
	-DTOUCH_CS=-1

	-D TFT_IPS=0
	-D TFT_COL_OFS1=0
	-D TFT_ROW_OFS1=0
	-D TFT_COL_OFS2=0
	-D TFT_ROW_OFS2=0

	-DSDCARD_CS=4
	-DSDCARD_SCK=18
	-DSDCARD_MISO=19
	-DSDCARD_MOSI=23

lib_ignore =
	SensorLib
	XPowersLib

[env:Awok-Mini]
extends = env:Marauder-Mini
board_build.partitions = support_files/custom_16Mb.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
build_flags =
	${env:Marauder-Mini.build_flags}
	-DLAUNCHER_WIFI_TX_POWER=44
