; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:lilygo-t-dongle-s3-tft]
board = esp32s3
board_build.partitions = support_files/custom_16Mb.csv
board_upload.speed = 921600
build_src_filter =${env.build_src_filter} +<../boards/lilygo-t-dongle-s3-tft>
build_flags =
	${env.build_flags}
	-DARDUINO_USB_MODE=1
	-DBOARD_HAS_PSRAM=1
	-DARDUINO_USB_CDC_ON_BOOT=1

	-DDEVICE_NAME='"Lilygo T-Dongle S3"'
	-DDISABLE_OTA

	-DHAS_1_BUTTON=1

    -DROTATION=1

	-DFP=1
	-DFM=1
	-DFG=2

	-D TFT_DATABUS_N=0        # Arduino_HWSPI
	-D TFT_DISPLAY_DRIVER_N=0  # Arduino_ST7735
	-D	ST7735_GREENTAB160x80=1
	-D  TFT_WIDTH=80
	-D  TFT_HEIGHT=160
	-D  TFT_MOSI=3
	-D  TFT_SCLK=5
	-D  TFT_CS=4
	-D  TFT_DC=2
	-D  TFT_RST=1

	-D TFT_BL=38
	-D TFT_IPS=1
	-D TFT_COL_OFS1=26
	-D TFT_ROW_OFS1=1
	-D TFT_COL_OFS2=26
	-D TFT_ROW_OFS2=1

	-DUSE_SD_MMC=1
	-D SDM=SD_MMC

	-DPIN_SD_CMD=16
	-DPIN_SD_CLK=12
	-DPIN_SD_D0=14
	-DPIN_SD_D1=17 # Not used, disabled in software
	-DPIN_SD_D2=21 # Not used, disabled in software
	-DPIN_SD_D3=18

	-DSDCARD_CS=PIN_SD_D3
	-DSDCARD_SCK=PIN_SD_CLK
	-DSDCARD_MISO=PIN_SD_D0
	-DSDCARD_MOSI=PIN_SD_CMD

lib_ignore =
	SensorLib
	XPowersLib


[env:lilygo-t-dongle-c5-tft]
board = esp32c5
board_build.partitions = support_files/custom_16Mb.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
build_src_filter =${env.build_src_filter} +<../boards/lilygo-t-dongle-s3-tft>
build_flags =
	${env.build_flags}
	-DARDUINO_USB_MODE=1
	-DBOARD_HAS_PSRAM=1
	-DARDUINO_USB_CDC_ON_BOOT=1

	-DDEVICE_NAME='"Lilygo T-Dongle C5"'
	-D DISABLE_OTA

    -DROTATION=1

    -DHAS_1_BUTTON=1

	-DFP=1
	-DFM=1
	-DFG=2

	-D TFT_DATABUS_N=0        # Arduino_HWSPI
	-D TFT_DISPLAY_DRIVER_N=0  # Arduino_ST7735
	-D	ST7735_GREENTAB160x80=1
	-D  TFT_WIDTH=80
	-D  TFT_HEIGHT=160
	-D  TFT_MOSI=2
	-D  TFT_MISO=7
	-D  TFT_SCLK=6
	-D  TFT_CS=10
	-D  TFT_DC=3
	-D  TFT_RST=1

	-D TFT_BL=0
	-D TFT_IPS=1
	-D TFT_COL_OFS1=26
	-D TFT_ROW_OFS1=1
	-D TFT_COL_OFS2=26
	-D TFT_ROW_OFS2=1

	-DSDCARD_CS=23
	-DSDCARD_SCK=6
	-DSDCARD_MISO=7
	-DSDCARD_MOSI=2

lib_ignore =
	SensorLib
	XPowersLib
