[env:reaper]
board = esp32s3
board_build.partitions = support_files/custom_16Mb.csv
build_src_filter =${env.build_src_filter} +<../boards/reaper>
build_flags =
	${env.build_flags}
	-D BOARD_HAS_PSRAM
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D ARDUINO_USB_MODE=1
    -D USE_HSPI_PORT=1

    -DOTA_TAG='"reaper_bruce"'
    -DDEVICE_NAME='"Bruce Reaper"'

    -D HAS_6_BUTTONS=1 # uses same HAS_5_BUTTONS logic
    -DLAUNCHER_GPIO_KEYS='{{"Esc", 21}, {"Right", 38}, {"Left", 39}, {"Down", 40}, {"Up", 41}}' # Choose among available GPIO to start Launcher when booting
    -D ROTATION=1

    -DPMIC_BQ25896=1
    -DGAUGE_BQ27220=1

    -D USER_SETUP_LOADED=1
    -D TFT_DATABUS_N=0        # Arduino_HWSPI
    -D TFT_DISPLAY_DRIVER_N=1  # Arduino_ST7789
    -D TFT_RGB_ORDER=0
    -D TFT_WIDTH=170
    -D TFT_HEIGHT=320
    -D TFT_BL=6
    -D TFT_RST=16
    -D TFT_DC=15
    -D TFT_MISO=8
    -D TFT_MOSI=18
    -D TFT_SCLK=17
    -D TFT_CS=7
    -D TFT_IPS=1
    -D TFT_COL_OFS1=35
    -D TFT_ROW_OFS1=0
    -D TFT_COL_OFS2=35
    -D TFT_ROW_OFS2=0

    # SD CARD
    -D SDCARD_CS=3
    -D SDCARD_SCK=17
    -D SDCARD_MISO=8
    -D SDCARD_MOSI=18


