[env:lilygo-t-hmi]
board = esp32s3
board_build.partitions = support_files/custom_16Mb.csv
board_upload.speed = 921600
build_src_filter =${env.build_src_filter} +<../boards/lilygo-t-hmi>
build_flags =
	${env.build_flags}
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1

	-DDEVICE_NAME='"Lilygo T-HMI"'
	-DOTA_TAG='"t-hmi"'

	-D HAS_TOUCH=1
	-D HAS_RESISTIVE_TOUCH=1
	-D TOUCH_XPT2046_SPI
	-D TOUCH_CTRL_XPT2046=1 # hal_touch_init/hal_touch_read (src/hal/inputs/touch.cpp)
	-D CYD28_TouchR_IRQ=9
	-D CYD28_TouchR_MISO=4
	-D CYD28_TouchR_MOSI=3
	-D CYD28_TouchR_CLK=1
	-D CYD28_TouchR_CS=2

	-DANALOG_BAT_PIN=5

	-D USE_SD_MMC=1
	-D SDM=SD_MMC
	-D PIN_SD_CMD=11
	-D PIN_SD_CLK=12
	-D PIN_SD_D0=13

	-D HAS_SCREEN=1
	-D ROTATION=3

	-D USER_SETUP_LOADED=1
	-D TFT_DATABUS_N=2        # Arduino_ESP32PAR8Q
	-D TFT_DISPLAY_DRIVER_N=1  # Arduino_ST7789
	-D TFT_WIDTH=240
	-D TFT_HEIGHT=320
	-D TFT_RGB_ORDER=TFT_BGR
	-D TFT_INVERSION_OFF=1
	-D TFT_CS=6
	-D TFT_DC=7
	-D TFT_RST=-1
	-D TFT_WR=8
	-D TFT_RD=-1
	-D TFT_D0=48
	-D TFT_D1=47
	-D TFT_D2=39
	-D TFT_D3=40
	-D TFT_D4=41
	-D TFT_D5=42
	-D TFT_D6=45
	-D TFT_D7=46
	-D TFT_BL=38

	-D TFT_IPS=0
	-D TFT_COL_OFS1=0
	-D TFT_ROW_OFS1=0
	-D TFT_COL_OFS2=0
	-D TFT_ROW_OFS2=0

lib_ignore =
	SensorLib
	XPowersLib
