; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-core]
board = esp32
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.partitions = support_files/custom_16Mb.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_upload.maximum_ram_size = 532480
build_src_filter =${env.build_src_filter} +<../boards/m5stack-core>
build_flags =
	${env.build_flags}
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-mfix-esp32-psram-cache-strategy=memw

	-DDEVICE_NAME='"M5Stack Core Series"'
	-DOTA_TAG='"core"'


	-DUSE_CARDKB2=1
	-DCARDKB2_SDA=21
	-DCARDKB2_SCL=22

	-DROTATION=2

	-DHAS_3_BUTTONS=1

	-D TFT_DATABUS_N=0        # Arduino_HWSPI
	-D TFT_DISPLAY_DRIVER_N=24 # Arduino_ILI9342
	-DM5STACK=1
	-DTFT_WIDTH=320
	-DTFT_HEIGHT=240
	-DTFT_MOSI=23
	-DTFT_MISO=19
	-DTFT_SCLK=18
	-DTFT_CS=14
	-DTFT_DC=27
	-DTFT_RST=33
	-DTFT_BL=32

	-D TFT_IPS=1
	-D TFT_COL_OFS1=0
	-D TFT_ROW_OFS1=0
	-D TFT_COL_OFS2=0
	-D TFT_ROW_OFS2=0

	-DSDCARD_CS=4
	-DSDCARD_SCK=18
	-DSDCARD_MISO=19
	-DSDCARD_MOSI=23

lib_deps =
	${env.lib_deps}
	m5stack/M5Unified @ ^0.2.17

lib_ignore =
	SensorLib
	XPowersLib

[env:m5stack-core-4Mb]
extends=env:m5stack-core
board_build.partitions = support_files/custom_4Mbcore.csv
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
board_upload.maximum_ram_size = 327680


