; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-paper-s3]
board = esp32s3
board_build.partitions = support_files/custom_16Mb.csv
board_build.arduino.memory_type = qio_opi
board_upload.speed = 921600
build_src_filter =${env.build_src_filter} +<../boards/m5stack-paper-s3>
build_flags =
	${env.build_flags}
	-DM5STACK
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1

	-DDEVICE_NAME='"M5Stack Paper S3"'
	-DOTA_TAG='"paper"'
	-DOTA_EXTRA='"esp=S3"'

	-DUSE_M5GFX=1
	-DE_PAPER_DISPLAY=1
	;-DUSE_CANVAS=1

	-DROTATION=0
	-DDIMMER_SETUP=0

	-DFP=2
	-DFM=4
	-DFG=6

	-DHAS_TOUCH=1
	-DTFT_WIDTH=540
	-DTFT_HEIGHT=960

	-DSDCARD_CS=47
	-DSDCARD_SCK=39
	-DSDCARD_MISO=40
	-DSDCARD_MOSI=38


lib_deps =
	${env.lib_deps}
	m5stack/M5Unified @ ^0.2.17

lib_ignore =
	SensorLib
	XPowersLib
	GFX Library for Arduino


[env:m5stack-paper]
board = esp32
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.partitions = support_files/custom_16Mb.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_upload.maximum_ram_size = 4521984
build_src_filter =${env.build_src_filter} +<../boards/m5stack-paper-s3>
build_flags =
	${env.build_flags}
	-DARDUINO_M5STACK_PAPER
	-DM5STACK
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-mfix-esp32-psram-cache-strategy=memw

	-DDEVICE_NAME='"M5Stack Paper"'
	-DOTA_TAG='"paper"'
	-DOTA_EXTRA='"esp=32"'

	-DUSE_M5GFX=1
	-DE_PAPER_DISPLAY=1

	-DROTATION=0
	-DDIMMER_SETUP=0

	-DFP=2
	-DFM=4
	-DFG=6

	-DHAS_TOUCH=1
	-DTFT_WIDTH=540
	-DTFT_HEIGHT=960

	-DTFT_MOSI=12 # uses same SDBus, need it to make it work
	-DSDCARD_CS=4
	-DSDCARD_SCK=14
	-DSDCARD_MISO=13
	-DSDCARD_MOSI=12


lib_deps =
	${env.lib_deps}
	m5stack/M5Unified @ ^0.2.17

lib_ignore =
	GFX Library for Arduino

