; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

#################################### EStart OF LILYGO MODELS #######################################
[env:lilygo-t-lora-pager]
board = esp32s3
board_build.arduino.memory_type = qio_opi
board_build.partitions = support_files/custom_16Mb.csv
build_src_filter =${env.build_src_filter} +<../boards/lilygo-t-lora-pager>
build_flags =
	${env.build_flags}
	-DARDUINO_USB_MODE=1
	-DBOARD_HAS_PSRAM=1
	-DARDUINO_USB_CDC_ON_BOOT=1

	-DDEVICE_NAME='"Lilygo T-LoraPager"'
	-DOTA_TAG='"t-lora-pager"'

	-DRESERVED_NAV_KEYS='"wasd"' # Up/Down/Prev/Next — see interface.cpp InputHandler
	-DLAUNCHER_GPIO_KEYS='{{"Encoder Btn", 7}}' # Choose among available GPIO to start Launcher when booting

	-DROTATION=3

	-DHAS_ENCODER=1
	-DHAS_KEYBOARD=1

	-DPMIC_BQ25896=1
	-DGAUGE_BQ27220=1

	-D TFT_DATABUS_N=0        # Arduino_HWSPI
	-D TFT_DISPLAY_DRIVER_N=2  # Arduino_ST7796
	-DTFT_WIDTH=222
	-DTFT_HEIGHT=480
	-DTFT_BL=42
	-DTFT_MISO=33
	-DTFT_MOSI=34
	-DTFT_SCLK=35
	-DTFT_CS=38
	-DTFT_DC=37
	-DTFT_RST=-1

	-DTFT_IPS=1
	-DTFT_COL_OFS1=49
	-DTFT_ROW_OFS1=0
	-DTFT_COL_OFS2=49
	-DTFT_ROW_OFS2=0

	-DSDCARD_CS=21
	-DSDCARD_SCK=35
	-DSDCARD_MISO=33
	-DSDCARD_MOSI=34

lib_deps =
	${env.lib_deps}
	mathertel/RotaryEncoder @1.5.3
	adafruit/Adafruit TCA8418 @ ^1.0.2
